services:
  web:
    build:
      dockerfile:
        Dockerfile.web
      context: .
    working_dir: "/menu"
    volumes:
      - .:/menu

    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always

